### ISSUE TITLE
Saturating math -> checked math?

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1141]
A number of places in soroban (fees, metering, ledger arithmetic) use saturating arithmetic to avoid the risk of over/underflow. This is _often_ correct (or harmless) but not always -- it also opens up the potential for two problems:

  1. Violating intended arithmetic identities (a - b makes c, then c + b should make a, but .. maybe now it doesn't)
  2. Hiding bugs (a - b underflows because we let b get too big .. but now we don't notice)

The next-best alternative is the _checked_ variants of all the currently-saturating arithmetic. I think in most of the places we use saturating, checked would work as well or better. We might want to add a helper trait that provides abbreviations for `checked_{add,sub,mul,div}(...).ok_or(Error::from_type_and_code(ScErrorType::Value, ScErrorCode::ArithDomain))`?

**Comment by graydon** [comment]
cc @MonsieurNicolas and also @dmkozh who no doubt has opinions about this in fees!

**Comment by dmkozh** [comment]
We could do that, but I'm just not sure if that's the most useful thing to do (specifically for fees). It makes the bridge and core side implementation more complex, because now the fee computation becomes fallible and we need some code to handle that.  It also makes the library much more complex. 
Since the maximum valid fee has an upper bound that is way less than `i64::MAX`, it seems fine to me to have imperfect math for the edge cases because we can't include transactions that get to these cases. Underflows also don't seem possible.

**Comment by MonsieurNicolas** [comment]
This seems fine. I guess we need the proper checks anyways outside of fee computation, so if we assume that no account can pay even "as little" as `i64::MAX` we're good

**Comment by MonsieurNicolas** [comment]
so for fees I guess this is fine -- what about other places?

**Comment by dmkozh** [comment]
> so for fees I guess this is fine -- what about other places?

A quick audit shows that we're otherwise using saturating arithmetic for budget arithmetic, which is a very similar case to the fees - we don't want it to be fallible because failure is kind of meaningless (if you reach u64::MAX instructions/memory charged, you should fail anyway due to running out of budget). The only remaining small case is ledger seq maths for the rent bumps, which has to be addressed *somehow* when we get to `u32::MAX` ledger; but we probably don't need to worry about that for now.

**Comment by jayz22** [comment]
We also have a few places of using plain math ops (`*`) instead of saturating/checked version, e.g. https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/host/metered_map.rs#L42-L64 (thanks to @C0x41lch0x41 for pointing out). It is a good idea to expand this issue to also audit for that.

**Comment by dmkozh** [comment]
> We also have a few places of using plain math ops (*) instead of saturating/checked version

Saturating budget ops instead of just raw ones sounds fine. Just let's not overthink it with checked ops (for aforementioned reasons).
