### ISSUE TITLE
[test] over-large or otherwise invalid wasms

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1145]
A variety of places in wasm allow over-large or otherwise invalid inputs. Many of these will be rejected before they make it to us, and many will be rejected by wasmi itself. But we should have a test that checks we reject as many as we can think of ourselves:

- [x] corrupt metadata custom section
- [x] floating point instructions
- [ ] SIMD instructions, other post-MVP extensions
  - [x] multi-value 
- [x] very large import table that imports the same host functions over and over
- [x] importing nonexistent host functions
- [x] multiple memories
- [x] exporting nonexistent functions
- [ ] invalid table entries
  - [x] FuncRef
  - [ ] ExternRef 
- [x] start functions (these are banned)
- [ ] invalid const-expressions and active table references in elements table
- [ ] invalid const-expressions in active data segment mode
- [x] multiple data-count sections, sections with an invalid count
- [ ] very large versions of every section type:
  - [x] `Custom`
  - [ ] `Type`
  - [x] `Import`
  - [ ] `Function`
  - [ ] `Table`
  - [x] `Memory`
  - [x] `Global`
  - [x] `Export`
  - [x] `Start`
  - [x] `Element`
  - [x] `Code`
  - [x] `Data`
  - [x] `DataCount`

**Comment by dmkozh** [comment]
A general comment for this issue is that if something can't be statically excluded, then we should cover it via a respective contract call.

Also, a few additions:

- [ ] Invalid host function imports (wrong number/type of args )
- [ ] Invalid contract function exports (wrong number/type of args)
- [ ] Incorrect argument types for host function call (i32 instead of i64) - likely runtime only
