### ISSUE TITLE
Public `EnvBase` functions should be infallible in `Guest`

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#1243]
Currently the SDK implements `EnvBase` functions and exposes them publicly as is. However, these functions are declared as returning `Result<>`, so this interface creates a false impression that these functions can return an error. This has been confusing enough to even slip into our own tests (https://github.com/stellar/rs-soroban-env/blob/743574451a4fe17e508fa0035b5d7a26b1e2ef75/soroban-test-wasms/wasm-workspace/linear_memory/src/lib.rs#L50). 

We should hide `EnvBase` and add public infallible wrappers around its functions.

**Comment by graydon** [comment]
I think `EnvBase` is a bit of a red herring here. All `soroban_env_commom::Env` methods are also "technically fallible", returning `Result<..., EnvBase::Error>` which has 3 significantly-different ways it gets used:

  1. `Result<..., Infallible>` when building against `Guest`: the type system is telling you it's impossible to observe `Err(..)` because your enclosing VM will trap before you see it.
  2. `Result<..., HostError>` when building against `Host` natively for local testing, where the methods get wrapped in an SDK method that rejects any error with `reject_err` in the SDK that calls `EnvBase::escalate_error_to_panic` and unwinds, _transforming_ `Result<..., HostError>` into `Result<..., Infallible>` and thereby emulating the `Guest` mode.
  3. `Result<..., HostError>` when being called from another host function, including but not limited to a native contract or a unit test. In all these cases we actually want to observe `Err(...)` values, log them, inspect them, return them, etc.

The SDK doesn't (visibly?) re-export `EnvBase` but it also doesn't (visibly?) re-export the fallible `soroban_env_common::Env` interface. It exports its own `soroban_sdk::Env` type, which has inherent methods that are not fallible, and also has a whole other set of wrapper types it provides (it doesn't expose most of the types used by, or functions mentioned in, the `soroban_env_common::Env` interface at all).

But we can (and some of our tests do) explicitly import `soroban_env_common::Env` and use it to furnish that interface on the SDK's `Env` (eg. look at tests that `use` both the SDK and `soroban_env_common::Env as _`, such as `hostile.rs`)

**Comment by leighmcculloch** [comment]
@graydon So in the example at the top of the issue where .is_err() is being called on a fn that'll never return error, that's a `Result<_, Infallible>`?

It's a shame that clippy isn't reporting that we're calling is_err on a infallible.

**Comment by graydon** [comment]
(given we're pretty much unable to "fix" this, closing)
