### ISSUE TITLE
Charge for allocation of new `ParsedModule`

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1372]
https://github.com/stellar/rs-soroban-env/pull/1359#discussion_r1539882823

**Comment by graydon** [comment]
Actually I am going to have to revert this -- it doesn't work and isn't necessary. It doesn't work because the existing structure is part of Vm::new and is put in an Rc there with Rc::new but not separately metered, so starting to meter it breaks replay. And it's not necessary since it's actually counted as part of the constant term in the cost of instantiation (or now parsing).
