### ISSUE TITLE
Host reject ScVals that are invalid

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#223]
Supersedes https://github.com/stellar/rs-stellar-contract-env/issues/221 https://github.com/stellar/rs-stellar-contract-env/issues/222

Dependent on https://github.com/stellar/rs-stellar-xdr/issues/106

cc @graydon @jonjove @jayz22

**Comment by graydon** [comment]
We actually can't call `<ScVal as xdr::Validate>::validate` on `ScVal`s entering the system because that's not a metered function; but we do already perform equivalent validations during `ScVal` injections. We have a test for the symbol case but seemingly not the map-order case. I'll add another test.
