### ISSUE TITLE
Copy/move host test vector contracts from SDK repo to this repo

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#329]
It appears that the stellar-env-host crate has tests that depend on the wasm outputs of the SDK test contracts. 

This is not ideal because this has caused at times for us to have test contracts in the SDK repo that we're bespoke for a specific host test and otherwise made little sense to SDK developers or people who work only in the SDK repo.

We should keep test vectors for the host near the host. I think we should move or copy the test contracts that the host relies on from the SDK repo to the host repo.  

Advantages of doing this:
- host test vectors are changed on a cadence that makes sense for the core team.
- the host can maintain test vectors that use different versions of the SDK.

cc @graydon @jayz22 @jonjove @sisuresh

**Comment by leighmcculloch** [comment]
I suggest we do this soon while the test vectors still work.

**Comment by leighmcculloch** [comment]
I think we should put them at this location in the repo to keep them as close as possible to the host and covered by the hosts CODEOWNERS:
- `/stellar-env-host/test-contracts/`

**Comment by jonjove** [comment]
I just ran into this problem when trying to update the interface version, specifically for the test https://github.com/stellar/rs-soroban-env/blob/556c75fa80e3b6e5ff3dc09443b9dc66e3111a40/soroban-env-host/src/test/invocation.rs#L73-L101

In order to make progress on https://github.com/stellar/rs-soroban-env/pull/319, I commented that test out since there was a big distinction between what was in the WASM and what was in the test case. It should be fixed as part of this work.

**Comment by leighmcculloch** [comment]
The fix for ☝️ should be to copy the test contract from the SDK repo at the commit before the contract was changed, which is: https://github.com/stellar/rs-soroban-sdk/commit/38ff4678dabb8c739c2f25d5c5dff8886851f04d

**Comment by leighmcculloch** [comment]
Unassigning myself because I think this should be done by the folks writing the tests in the `soroban-env-host` crate that need the test vectors, i.e. @graydon or @jayz22.
