### ISSUE TITLE
Fixed size big integers?

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#339]
Should `BigInt` receive a maximum bit-size parameter? Should we support some fixed size integers like u256? Are there crates that can provide some of this functionality for us automatically at reasonable performance/size?

Related to https://discord.com/channels/897514728459468821/1007337480179171441

**Comment by leighmcculloch** [comment]
I think we need bitsize caps for interior, otherwise developers will need to check for overflow themselves, which will lead to errors. 

I think it's reasonable for us to add a bit size to `BigInt<BITSIZE = ...>` with a reasonable default value. We would need to add the bitsize to the XDR so that the aspect of the type carries into inputs, etc, and so the host can validate.

This approach has a few benefits:
- BigInts of different max bitsizes aren't implicitly interoperable from the compilers pov, but we can have fallible conversion functions, mirroring Rusts approach to its own integer interactions. 
- We can type alias BigInt<256> to U256.
- Users can use other integer sizes if they need, and we don't special case code using one size over others. 

There are downsides:
- While we can add functionality to BigInt for specific sizes like U256 if we need to, we can't specialize functions shared by all sizes. If we really want specialization though we could macro generate impls for a range of useful bitsizes and then hand code specifics.

**Comment by leighmcculloch** [comment]
Somewhat related to this we probably also need an unsigned version of BigInt.

**Comment by jayz22** [comment]
Why can't this be done at the sdk level? Similar to how the sdk `vec` takes in `<T>` to ensure all elements are of the same type?

**Comment by leighmcculloch** [comment]
It could, but that's adding a lot of logic to WASM files that could be simply be applied at the host layer. Vec is a bit different, since T can be a complex type. With BigInt the constraint is well defined.

Is we're to go ahead with this I suggest we list out what the SDK interface is, then see what needs changing in the host to support it. Or, we could do as Jay suggests and start by implementing this in the SDK only to start as an experiment.

**Comment by sisuresh** [comment]
No longer relevant because we [removed](https://github.com/stellar/rs-soroban-env/pull/581) BigInt support.
