### ISSUE TITLE
Implement get_current_call_stack

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#359]
### What problem does your feature solve?

See https://github.com/stellar/stellar-protocol/issues/1289.

### What would you like to see?

A host function with a name like `get_current_call_stack` which returns a vector-of-vectors where the inner vector contains `[contractID, function]`.

### What alternatives are there?

There are many other reasonable return values for `get_current_call_stack` mentioned in https://github.com/stellar/stellar-protocol/issues/1289 and I'm open to any of those.

**Comment by sisuresh** [comment]
Should this return a vector-of-vectors, or the SHA256 hash of the vector-of-vectors? I'm leaning towards a hash for these reasons -

1. The vector is meant to be included in a signature. The contents of the vector have no good reason to be used and a hash would make it more difficult to misuse the call stack. The counter argument to this though is a hash makes the signature payload more opaque, and the scenario with the empty call stack would have to be specified.
2. I'm not sure how the sdk should return the call stack if it isn't a hash. It would have to convert the `Object` from the host to a `Vec<Vec<EnvVal>>` since the inside vector contains a `Symbol` and a `Hash`. @leighmcculloch is this possible at the moment in the SDK?

**Comment by leighmcculloch** [comment]
> 1\. the scenario with the empty call stack would have to be specified

I don't think it needs to be specified any more or less than any other call stack. An empty call stack would just be an empty list. Even if the empty call stack was a zero byte array, the sha256 of a zero byte array is well defined.



> 2\. I'm not sure how the sdk should return the call stack if it isn't a hash. It would have to convert the `Object` from the host to a `Vec<Vec<EnvVal>>` since the inside vector contains a `Symbol` and a `Hash`. @leighmcculloch is this possible at the moment in the SDK?

A `Vec` of `Vec`s works just fine, but I would recommend using a `Vec<(Hash, Symbol)>` on the SDK side. It is equivalent, but it will mean you don't need `EnvVal`. Basically any time we surface `EnvVal` in the API is a red flag, so if we're ever running into that, or see that anyway in the API, call it out and we can tweak it away.

**Comment by leighmcculloch** [comment]
I don't think the options are mutually exclusive. If all we need is the hash right now, let's expose the hash. If we ever need the full call stack we can add it. Same goes with the reverse.

**Comment by leighmcculloch** [comment]
A hash assumes always the full call stack is being signed for, rather than some subset. I don't know if that is important. Is that important?
