### ISSUE TITLE
Update native token auth

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#360]
### What problem does your feature solve?

Authorization has been changing in soroban-token-contract and we need to mirror those changes in the native version.

### What would you like to see?

Similar changes to https://github.com/stellar/soroban-token-contract/pull/86.

### What alternatives are there?

N/A

**Comment by sisuresh** [comment]
@jonjove correct me if I'm wrong, but I think this issue is required for us to update https://github.com/stellar/soroban-examples to use the token contract with the new auth.

It looks like the liquidity pool uses the native token contract, but interfaces with it using the non-native contract code. Is my understanding right here? If so, I'll make this issue a higher priority.

**Comment by leighmcculloch** [comment]
Given that the token contract is native now what is the future if the token contract in the soroban-token-contract repo? Is it just an example now?

**Comment by jonjove** [comment]
@sisuresh you are correct, we will need to do this to update all the examples (but we can update all the examples other than liquidity pool without doing this, I think).

@leighmcculloch My current belief is that soroban-token-contract will move into soroban-examples as just another example, but I'm not 100% sure about that since I'm still thinking about how native contracts fit into the big picture.

**Comment by sisuresh** [comment]
Closed by #394
