### ISSUE TITLE
Question: Why does the `bigint_bits` function return `u64`?

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#423]
@jayz22 @graydon Why does the `bigint_bits` function return `u64`? In Rust built-in primitive types like u32, u64, all define their number of bits in `u32`. I find it highly unlikely our BigInt type would realistically be able to hold more than u32::MAX bits either.

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-soroban-sdk/pull/582#discussion_r967572968_

**Comment by jonjove** [comment]
It originates from https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#method.bits. In theory, having more than `u32::MAX` bits isn't too unreasonable (it's only 0.5 GiB, easily in range for a modern computer). In practice, that seems really large for soroban. I'm not sure how we should unify those two realities.

**Comment by jayz22** [comment]
I think it's better to keep u64 for now rather than putting an implicit size limit, since eventually we might swap out the implementation of the `bigint` altogether.

**Comment by graydon** [comment]
(Also note that the only types of untagged, non-RawVal "actually a number" we can return are i64 or u64. If you want to transport a u32 across the boundary you actually put it in a RawVal and tag it. It's not clear to me from an SDK or codesize perspective which cases we prefer the host returning such plain untagged numbers and which cases we prefer returning a RawVal-the-host-guarantees-to-be-some-other-smaller-number-type. @leighmcculloch any preference?)

((It is also not clear to me which cases really warrant u32 / i32 as members of RawVal at all, rather than just using u63. I guess for unboxed negative values i32 it makes sense, and u32 is just there for symmetry? Hmm.))

**Comment by leighmcculloch** [comment]
I think u32 might be valuable for cases where that size is what you plan to use internally, it means you can make it part of your interface and ensure people pass that size. It would be awkward to deal with receiving u63 and downcasting all the time. I'm not strongly opposed to dropping u32 though and telling people to use i64. Developers already have to downcast for u8 and u16 values.

It is worth noting that _only_ i64 gets the benefit of u63 encoding. If you want to use a u64 you always use an object. This is so that there is always a 1-1 mapping between types to prevent foot guns like "tests only test positive values then explodes on a negative value" type of thing.

**Comment by leighmcculloch** [comment]
If we think u64 is likely to have more utility than i64 then we could change which type uses u63.
