### ISSUE TITLE
Object type Debug implementations should render contents

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#442]
The Debug implementation for Vec's that gets triggered by DebugEvent formatting is a very simple `Object(Vec(3))` where the `3` is the length.

We should render something that shows the individual elements as well so that DebugEvents containing Vec's are more meaningful.

I assume the same needs doing for Maps.

---

>@graydon It is worth noting that the debug output of Vecs is pretty underwhelming in debug events ☝🏻. In the SDK Vec's have a very different output as their Debug implementation outputs every individual element. Maybe we should do something similar in the host?

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-soroban-sdk/issues/611#issuecomment-1248691109_

**Comment by leighmcculloch** [comment]
This issue should apply to all ScObject types.

**Comment by graydon** [comment]
Actually 3 is the object ID, not the length! Maybe we should put a `#3` or something.

It's difficult to do this currently because the host is not kept alive by the `DebugEvent`s. The event buffer gets snapshotted into `HostError` which is then formatted lazily as a string when-and-if it's caught, quite late, and the host may be long gone by then. Keeping the host alive by holding a reference to it in the `DebugEvent` or `HostError` is possible, but even if we did that it's not necessarily the case that the host objects referenced are still alive at the time of a catch either (when we roll back a host, for example, objects get dropped).

We could format eagerly (when the event is saved to the log) but that would make the log operation much more expensive in cases when nobody looks at the results, and also require keeping strings in the log which .. I've been trying to avoid doing.

Another dimension of this is that a general value might be quite _big_ and we don't necessarily want to pay the storage costs nor spam the debug log with gigantic stringified values even in debug cases. There ought to be some kind of size limit / data elision on printing, even if we go a little ways into printing.

I'm not going to close this WONTFIX but .. I feel a little stuck with the current design pressures. I think I'd like to at least put this on hold until we decide on RawVal size and repertoire, whether we're going to support slices/user strings, and maybe whether/how we are going to define a "small object" type. Maybe we can find something good enough for users with some combination of those features, like "capture small objects by value, by snapshotting their XDR type and storing it to the side of the log buffer". Or maybe we need to never drop objects on rollback or something. Unclear.

One question for @leighmcculloch : would you be ok with this behaving differently in production vs. local testing? It's easier to tolerate expensive diagnostic stuff in the local testing case as it's not being metered / not a DoS vector.

**Comment by leighmcculloch** [comment]
>It's difficult to do this currently because the host is not kept alive by the DebugEvents.

I don't think the DebugEvents need to keep the host alive. I think we could do with a function on debug events, or somewhere, that takes a host and a debug event, and generates a string. This way the debug events don't need to keep the host around. But there's a way to rehydrate the full representation.

I definitely think it's okay for this behavior to not be available in the env compiled for core. We only need it in the compile version used by the SDK and CLI. So resources should be less of a concern I think. I also think it's fine to cap some objects output. Such as a Vec, it could simply truncate with a `...` past 200 elements or something like that.

The rollback issue seems like the big problem. If we add the function I describe, we'd be using it after invocations have happened and ideally we could use it regardless of rollback.

**Comment by graydon** [comment]
Ok. We'll limit this to local-testing mode and either eagerly format events on logging or else copy the host object array into an optional field on the captured event buffer so that it can lazily format them when-and-if anyone prints them.

(I experimented with making the host object pool sharable / detachable but it has to be Sync for Wasmi to be happy and this makes accessing it in the non-error case 10-100x slower, so I think it's a bad trade)

**Comment by leighmcculloch** [comment]
Agreed on that being a bad trade. Eagerly formatting events just in that local-testing mode sounds better in terms of tradeoffs.

**Comment by graydon** [comment]
Done in https://github.com/stellar/rs-soroban-env/pull/806
