### ISSUE TITLE
Support DebugEvents in WASM builds

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#447]
The SDK provides logging functionality that is only available in debug builds. That logging functionality creates DebugEvents by calling this function:

- `log_static_fmt_general `

That function isn't implemented for the Guest Env though, so when a contract is built using the dev profile the debug events are lost.

We should add support for debug events so that contract developers can see debug events / logs when using the CLI tool or when contract importing a dev profile built contract for testing.

**Comment by leighmcculloch** [comment]
cc @graydon I'm not sure when we can schedule this. I had hoped to support this style of debug event logging for Meridian, but I failed to understand the current intended limitations with debug events. I understand if this is a post-Meridian thing.

**Comment by graydon** [comment]
It's not so much a huge amount of work as something I want to make sure we do intentionally / carefully. This functionality is turned of for reasons, and turning it on / plumbing it through should address those reasons.

There are 3 considerations:

  - The lifetime of guest memory: We currently embed a full copy of the host's event buffer (at the time of error) in `HostError`, along with a stacktrace, when we generate a `HostError`, so that we can print it to the user when/if they get a `Debug` dump in a panic. `HostError` currently does not hold onto either a `Host` or a `Vm`, so any values in an event struct have no `Host` or `Vm` to "resolve" against. This is incidentally the same reason that a host-object reference in a debug error message, when you format it, does not resolve to a "full" object, but just an object-handle number wrapped in an object type code name. Because it's just a context-free `RawVal`, no idea what `Host` or `Vm` it should resolve against. They might even have been torn down by the time you're dumping the `Debug` view of the event. If we embed a guest linear-memory address in an event (as the address of a format string for a log message), we would just be making this worse. We can do it with host static strings only because they're constant over the life of the OS process -- they always outlive the host anyways. We could copy guest memory into a longer-lived value (eg. a dynamic String) but that would cost much more at event-logging time (doing a memcpy at least, if not a full string-format, of data we probably want to ignore/discard 99% of the time) and also be a new way for guests to fragment host memory. So we'd probably want to make this optional / only turned on in debug builds of the host or something.
  - Exposure to the string formatting library: we're using a _very_ simple dynamic string formatter that is probably safe to expose to user input, but it's still a new attack vector, and "format strings exposed to user input" is an old favorite channel for security vulnerabilities. We'd want to be very, very sure about it.
  - Determinism: we'd want to be sure that users couldn't observe their own debug events, i.e. make sure string formatting doesn't become part of the contract between guest and host for deterministic replay.
  - Wasted code in production wasm builds: presumably users will want to compile-out all of this when building their contracts in "release mode". I was kinda using the wasm-vs-native (env-equals-guest-vs-host) distinction as the boundary indicating that, but it sounds like that's not the correct indicator. We should be sure to pick an indicator that avoids compiling format strings and no-op formatting calls into production contracts.

None of these are dealbreakers. I think probably the first one is the one I'm most uncertain about. If we could find a feature flag or cfg value we're comfortable hanging it on -- one that will definitely be turned on when users are doing local testing, but definitely be turned off on the host when building it for production -- I'd be ok having a variant of debug events that's slow and just copies a guest string into a host String, formats a message, and stores it. I just want to be sure we don't inadvertently put that into production builds.

**Comment by leighmcculloch** [comment]
I think we can address most of the concerns by saying that this feature is never enabled inside stellar-core, but it is a feature that can be enabled on the `stellar-env-guest` and `stellar-env-host` crates. By default the SDK will enable it for contract tests, and wasm debug builds.

The on-chain host env could simply panic if a contract tries to use these functions.

If we do this model, then I think pushing the fmt string into a `String` would be fine.

This will give the user the best experience when testing off chain, but will have zero impact on chain.

Wdyt?

**Comment by graydon** [comment]
Yeah, can probably make that work. From the perspective of minimizing the number of annoying feature flags, how would you like to indicate this?

**Comment by leighmcculloch** [comment]
Maybe a `debug` feature, that way we aren't adding new features for each individual thing, but anything debug related that is 100% never enabled in stellar-core can be bundled together.

**Comment by leighmcculloch** [comment]
Or `localonlydebug`.

**Comment by leighmcculloch** [comment]
Or even `offchain`.
