### ISSUE TITLE
Token Contract - Should it be possible to burn when frozen?

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#456]

**Comment by sisuresh** [comment]
Closed because we decided that it should be possible to for the admin to clawback (formerly called burn) a deauthorized (formerly called frozen) balance. This has been [implemented](https://github.com/stellar/rs-soroban-env/blob/d803b0922d1d9eb4d3cfde5e6d574c7776c23388/soroban-env-host/src/native_contract/token/contract.rs#L404).
