### ISSUE TITLE
Token init function names are confusing and unsafe

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#509]
https://github.com/stellar/rs-soroban-env/blob/35f752b6197173c8616034b4e3a587b2f530c49d/soroban-env-host/src/native_contract/token/contract.rs#L25-L37

These function names are reasonably confusing, and appear unsafe.

They're confusing because `init_wrap` contains no terminology that helps a user connect it with concepts that exist on classic Stellar. We've got three sets of concepts involved in this function:
- Assets – What we call assets on Stellar.
- Classic – The term we use in the metadata struct.
- Wrap – The term we use in the function name.

We need to build on the [ubiquitous language](https://martinfowler.com/bliki/UbiquitousLanguage.html) we already have that classic Stellar developer understand, when we're talking about and connecting those developers with the new token contract.

These functions also appear to be unsafe because you can call the wrong one on a token. The token should be able to identify what type of token it is, and perform the appropriate initialization in a single `init` function. This is a reasonably large footgun for a developer to have to know to call the correct one.

cc @jonjove @sisuresh

**Comment by sisuresh** [comment]
**Safety** -  Calling the wrong function will always fail - 
1. The `create_token_wrapper` host function will always call `init_wrap`, so there's no opportunity to initialize incorrectly.
2. For a regular token contract, `init_wrap` will always fail because it verifies the contract id is derived from the asset, which can only be true if `create_token_wrapper` was used.

**Naming** - I agree the naming should be improved. All references to `wrap` or `wrapper` should be removed, and we should settle on `asset` or `classic`. The ten character limit makes this difficult though.

**Separate init functions** - I split the initialize functions because they are conceptually different and the interface is cleaner (for example, the user should only provide an admin if this isn't an asset contract). I agree though that multiple init functions can be confusing, so combining them for the sake of usability makes sense to me.

**Comment by leighmcculloch** [comment]
Safety – this is great 👏🏻 . The reasoning for having separate init functions makes thanks, thanks for pointing out why that is.

For naming, can we use `asset`?

Given that `init_wrap`/`init_asset` is never callable from a contract successfully, because it is called directly by `create_token_wrapper`, how about we rename `init_token` to `init`, and then remove the other init function from the contract spec?

**Comment by leighmcculloch** [comment]
For example: https://github.com/stellar/rs-soroban-sdk/pull/695
