### ISSUE TITLE
Use system events

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#566]
We added a `system_event` [function](https://github.com/stellar/rs-soroban-env/blob/adad06ccef08c0ec7b6c29c5b741867e6d47e879/soroban-env-host/src/host.rs#L1055) in the host that was specified in CAP-0046-08, but we aren't using it anywhere. This was meant to be used in other host functions. One use case that we could add is publishing a `system_event` that contains the contractID when any of the contract creation host functions run.

**Comment by anupsdf** [comment]
Moved this to `Post V1` target milestone after discussing with @sisuresh

**Comment by jayz22** [comment]
We current emit a system event when updating a contract: https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/events/system_events.rs#L21

**Comment by dmkozh** [comment]
I think system events were a bit of an arbitrary design choice, which is why they haven't been utilized much. Even for the existing event (Wasm update), I don't think the information is useful  enough to be hashed into ledger - the ledger entry change already conveys exactly the same information. Unlike contract events, system events are not under control of the contract developers, so there is no way to e.g. disable them when they're unnecessary, and save some fees.
Going forward, we might want to formalize a subset of diagnostic events that are 'machine-readable'. This is probably the right bucket for the 'system' events, like doing a cross-contract call, managing the contract lifecycle etc. These could be enabled with a separate flag from the generic diagnostic events, so that e.g. a block explorer could ingest a bounded amount of system diagnostic events, instead of potentially much larger full set of events.
Even if we don't go the 'system diagnostic' events route, I think we should at least not add the new system events and just use the regular diagnostics instead.
