### ISSUE TITLE
Experiment and understand how we could "nativize" a popular contract

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/rs-soroban-env#632]
This came up several times.

There are a few drivers to actually get this done in v1.

Stateless contracts: can be a nice way to organically grow the list of "host functions" (in this case utility functions) without polluting the "global namespace".

Popular *and* simple contracts could be made substantially cheaper.

When combined with native ["proxy support"](https://github.com/stellar/rs-soroban-env/issues/631), there can be a path to something that looks like "shared base class" (native)  implementations with specialization done in WASM.

**Comment by dmkozh** [comment]
Now that the contracts are updateable, we can add a host fn that updates the source to a built-in implementation instead of Wasm hash. This would allow for controlled roll out of the updated implementation.

Alternatively, we could route certain Wasm hashes to the built-in implementation instead of the Wasm entry itself (via using e.g. the extension point we have in the contract code entry). This would allow for a seamless immediate update for all the instances.

For the stateless contracts we could just roll out a new contract (and it doesn't need to have the same interface as any existing contract).

It seems like we have enough extension points for now, so I'd close this particular issue. We might want to deploy a built-in utility contract before the release though, in order to provide some bundling and contract construction functionality that is not available via the regular protocol now.
