### ISSUE TITLE
Bugs / vulnerabilities due to cross contract calls

### ISSUE THREAD

**Issue by tamirms** [stellar/rs-soroban-env#637]
In ethereum although there is a standard ERC20 interface for tokens, not all token implementations conform to the standard. For example, some tokens revert when a transfer fails, while other tokens do not revert and instead return a false boolean indicating the transfer did not succeed. Differences among the ERC20 implementations have caused [bugs](https://soliditydeveloper.com/safe-erc20) in smart contracts which attempt to interact with any ERC20 token (e.g. uniswap).

The [SafeERC20 library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol) helps mitigate these issues but that is not fool proof. Consider the `transfer(dest, amount)` function, you would expect that, if the call succeeded, `amount` tokens will always be transferred to `dest`. However, a token contract might choose to charge potential fee on every transfer which is deducted from `amount`. A contract relying on `transfer(dest, amount)` always transferring `amount` tokens would potentially be broken in this scenario.

Generally speaking, if there are any assumptions about how another contract behaves and those assumptions are broken it can result in security vulnerabilities. [Reentrancy attacks](https://www.alchemy.com/overviews/reentrancy-attack-solidity) are a good example of this.

The reason I bring this up is that Soroban has a builtin Stellar Asset Contract and it is very easy to assume that, when you have a token client, you are interacting with the builtin Stellar Asset Contract. But that would be a false assumption because, the token client works on any Soroban contract which conforms to the token trait. So, even though there is a single Stellar Asset Contract implementation, the Soroban smart contract developer still needs to be aware of all the pitfalls from the ethereum world that I described above.

I believe this issue can also be compounded by Auth next. Consider the [Soroban <-> Ethereum bridge](https://github.com/stellar/starbridge/pull/102) which requires validators to sign a transaction that would allow participants to claim a cross-chain payment. In the Auth next world, validators need to be very careful when signing  transactions that would call the `xfer()` function on an arbitrary token contract. An attacker can craft a malicious contract which conforms to the token interface and uses the validator's authorization to steal funds from the bridge.

I think we could mitigate these threats by providing the option to create a contract client which asserts the contract conforms to a specific implementation (e.g. create a token client that asserts the token contract is the single asset contract).

More importantly we should include several Soroban examples which exhibit defensive smart contract practices. For example, I don't think we have any examples in our documentation of how to make contracts robust against reentrancy attacks.

**Comment by dmkozh** [comment]
> I think we could mitigate these threats by providing the option to create a contract client which asserts the contract conforms to a specific implementation 

I'm not sure about the exact interface, but we'll provide a way to determine what is the contract Wasm hash and whether it's a built-in contract. 

> An attacker can craft a malicious contract which conforms to the token interface and uses the validator's authorization to steal funds from the bridge.

I'm not sure I understand this. How do validators sign the transactions? (IIUC that's not something we have support for) More importantly, how exactly would a malicious token contract steal any funds? Wouldn't it need to be also bridged?

> For example, I don't think we have any examples in our documentation of how to make contracts robust against reentrancy attacks.

That's because reentrancy is simply not allowed currently. When/if we enable it, we'll try to make sure things are documented.

In general, while I understand these concerns, I wonder how much we can/should do to prevent them. Basically most of the issues are about not following the token interface. It's not obvious to me that 'bugged' tokens would get much value/use out of them (I've no idea why is this the case in the ETH world). I can always write a token that would redirect all the transfers to my address, but why would anyone ever use it?

**Comment by C0x41lch0x41** [comment]
> > An attacker can craft a malicious contract which conforms to the token interface and uses the validator's authorization to steal funds from the bridge.
> 
> I'm not sure I understand this. How do validators sign the transactions? (IIUC that's not something we have support for) More importantly, how exactly would a malicious token contract steal any funds? Wouldn't it need to be also bridged?

+1 to @dmkozh point. If I understand correctly the bridge design, bridge validators would need to add support for each coin that is bridged. So it is unlikely that a buggy token will be accepted.
I also think `Auth next` has the unique capability of letting the user accept exactly which contract is used. That prevents a user to blindly authorize a proxy that calls a malicious contract.

**Comment by C0x41lch0x41** [comment]
> In a world where contracts are allowed to be upgraded it
@dmkozh this is a more generic question, but what happens with `Auth next` if/when we allow contract to be updated? If you authorize contract A to call function fn(a, b, c) and then contract A is updated but fn keeps the same interface fn(a, b, c), will the authorization still be valid?

**Comment by dmkozh** [comment]
>  If you authorize contract A to call function fn(a, b, c) and then contract A is updated but fn keeps the same interface fn(a, b, c), will the authorization still be valid?

Yes, for now we wouldn't invalidate the signature. It's not impossible to add the implementation pointer to the signature payload, but I'm not convinced if that's generically useful. Maybe as an optional argument for some specific use cases?

IMHO the risk surface doesn't change significantly if we keep signatures valid. If the contract implementation is compromised, there is really no need to do anything fancy with user authorizations as it's just possible to transfer the contract's funds anywhere. Also note, that while the signature will stay valid, it's not possible to add/modify the subcontract calls. So if you've signed withdrawal of 10 XLM no matter how implementation changes host won't allow to withdraw more than 10 XLM from you.

**Comment by dmkozh** [comment]
> that the token contract is defined with a malicious xfer() function which will call xfer() on the xlm stellar asset contract to steal the lumens held by the bridge.

This is not possible. Both currently and with auth next contract only authorizes the direct calls on its behalf (we may probably extend that, but that won't ever happen implicitly). Hence the contract has to explicitly call `xfer` on the XLM token.

> The validator should not blindly use the invocations from the preflight endpoint. It needs to make sure the invocations don't include anything suspicious.

This is true for any signature and is a bit orthogonal to auth next (e.g. with your implementation the bridge could just accidentally sign the XLM withdrawal... but it shouldn't do that unless there are bugs). FWIW there is really no need to run preflight for every call and especially for the cases when on one hand the signature payload is stable and well-defined and on the other hand there are certain security risks due to automated signing (which is different from manual signing with the wallet). So the right thing to do here with auth next would probably be to build the signature payload manually and then sign it either separately or as a part of the whole transaction (at which point it would be logical for the bridge to just run the transaction).

**Comment by dmkozh** [comment]
>  there is a sample invocation listed with multiple invocations across different contract ids:

Exactly, in this case we authorize an `xfer` of 100 units of $token_id. If $token_id is not XLM, then it's not possible to withdraw XLM from me, no matter what $token_id implementation does.

> My point is that it's easier to authorize a top level invocation but when you have to analyze the behavior of other contracts which are invoked from the top level contract then it becomes more difficult.

You don't *have to* analyze behavior of the other contracts. If your intent is to always authorize the top-level call only, you can always do that by either building your invocation data manually (which is trivial for the case of a single top-level invocation and is easy to build helpers for) or by verifying that there is only a single invocation in the preflight response.
