### ISSUE TITLE
Possibly introduce a mutable version of `MeteredVector` and `MeteredMap`

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#707]
The current `MeteredVector` and `MeteredMap` hides away an important fact that these types are immutable underneath. (Previously we were wrapping them over the `im` containers so such a distinction were not necessary). 
These types have quadratic behavior which makes them unsuitable for some uses (e.g. non-small).
We should consider introducing mutable versions `MeteredMutVector` and `MeteredMutMap` that are both efficient to use and automatically metered. The main hurdle is to be able to override the `cmp` behavior such that it is fallible and metered.

**Comment by graydon** [comment]
Unsure about this. I think we currently have the following set of containers:

- Host objects themselves (currently `MeteredMap` and `MeteredVec`)
- The storage map (currently `MeteredMap`)
- The object vector (currently unmetered `std::vec::Vec`)
- The frame stack (same)
- The event buffer (same)
- The authorization context stack (same)

Are these the use-cases you have in mind also? Are there others?

One of the big reasons we use immutable rather than mutable types is that we want to be able to roll back the contents of a map to its previous state when we have a call / subtransaction fail. So for example host objects and the storage map probably can't be mutable because they would be impossible to roll back.

The other cases here are mutable vectors, not maps, and we don't compare them at any time to one another. We do mutate them, but in very restricted patterns (eg. "append only" or "stack discipline only") that directly admit a meaningful rollback operation ("null out failed entries" or "truncate the failed suffix").

**Comment by jayz22** [comment]
Closing this for now, as there are no urgent use case for it that are not covered above by immutable containers.
