### ISSUE TITLE
Auth: no way to sign an authorization that spans multiple invocations

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#801]
Stellar-core allows for multiple invocations to be included in an Operation. These invocations are intended to be processed atomically. i.e. They will all either succeed or fail. However, the auth system we have today provides no way to sign an auth for one invocation that is only valid with the other invocations.

I think this makes the degrades the usefulness of the "atomic" feature of multiple invocations in an Operation, because any meaningful invocation will have authorization, but any authorization inside a multiple invocation Operation can be separated out and submitted in isolation by anyone who sees it broadcasted.

**Comment by leighmcculloch** [comment]
cc @dmkozh

**Comment by dmkozh** [comment]
This is a general issue which IIUC affects any signed Operations (though it's worse for Soroban due to existence `ContractAuth` in addition to op signing) For now the generic workaround is to use the invoker auth, which should probably cover a significant chunk of the use cases (e.g. for deploying and initializing the contracts atomically).

I've been thinking that maybe we could provide something like optionally adding a transaction source account to the `ContractAuth` signature context. This would allow the transaction submitter to ensure that only they can use any `ContractAuth` entries, so it would be useful for the cases where a dapp gathers `ContractAuth` signatures from the users and sends transactions after collecting them. That however is not compatible with the channel accounts pattern that we're promoting. I'm not sure what else could be used as context though, any other ideas?

Beyond the context that we can provide, there is a lot of room for customization for the contract developers. That would probably not benefit from the built-in batching, but the intention for it is really to serve some simple cases of atomic initialization, not to necessarily to allow building arbitrarily complex execution chains.

**Comment by leighmcculloch** [comment]
Instead of introducing the source account into the mix, could we make the operation a node in the auth tree? Then in cases where top level invocations need binding, the user could include that node.

This would also be an elegant way for a user/wallet to require the top context of an invocation in their signature.

**Comment by leighmcculloch** [comment]
> This is a general issue which IIUC affects any signed Operations

This issue only affects Soroban operations, not existing Stellar operations. Existing Stellar operations are bound together in a transaction and are inseparable.

I think we need to make it possible to bind top level invocations together in a single ContractAuth, otherwise the utility of multi-invoke operations is very limited.

**Comment by dmkozh** [comment]
> could we make the operation a node in the auth tree?

What is 'operation', i.e. what could identify it? The best that comes to mind is really the source account and it's still pretty narrow.

> Existing Stellar operations are bound together in a transaction and are inseparable.

What about operations signed by a different account from the transaction account?

We could try allowing users signing multiple trees using a single signature, but that won't help much either, as it only allows tying auth for a single address. It doesn't seem like there is really a generic way of tying multiple independent signatures together; this probably needs to be solved on per-contract basis (if needed at all).

**Comment by leighmcculloch** [comment]
> What is 'operation', i.e. what could identify it

Operation = operation in a Stellar transaction. Operations can be identified uniquely, there's a hashing scheme we use to do that for claimable balances. But, I don't think the operation really needs identifying for Soroban and it would be better if it wasn't. The goal is to allow grouping multiple top level invocations by getting them into the same tree under some node.



> > Existing Stellar operations are bound together in a transaction and are inseparable.
> 
> What about operations signed by a different account from the transaction account?

Stellar operations are not signed. The payload signed for Stellar today is always the full transaction which contains all operations, hence a signature by any party on a Stellar transaction cannot be used without all operations together. 

If we can't solve this then I think we need to consider removing multi-invoke all together, because it's a security foot gun.

How about if we removed the bespoke multi-invoke feature, and instead replace it with a built-in contract that you can pass a series of invokes to, and it invokes them all with an optional auth Vec. It makes multi-invoke just a standard Soroban contract which can be authd to group, and it removed an edge case.

**Comment by dmkozh** [comment]
Multi-invoke is gone now. We still might want to do something about tx-envelope level signatures in p21, but that would be solving a bit different problem, so closing this issue.
