### ISSUE TITLE
Make vec_slice not copy a vec

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#871]
The `vec_slice` function is currently pretty expensive to use because it creates copies of the range of the vec being sliced.

This is surprising, since most of the time slicing native vec/array-like collection types results in a reference to the point in another vec.

We could make `vec_slice` behave like this.

_Note that this also might allow us to improve the vec iterator by being able to revert https://github.com/stellar/rs-soroban-sdk/pull/999 and returning it to simply doing a slice, although it might not be more performance for that specific use case, so we shouldn't change `vec_slice` only for the vec iter._

Related to https://github.com/stellar/rs-soroban-env/issues/696

**Comment by anupsdf** [comment]
Discussed this with @leighmcculloch and this is high priority issue that should be done in V1.

**Comment by graydon** [comment]
Since the iterator is no longer slicing this is less of an issue, and I think the cost and complexity of doing this on the host exceeds the potential win. Note that most PLs that have had default-refcounted slices have either abandoned it entirely as a bad trade, or abandoned it for small-vector cases, and all of our vectors will be small. In the rare case users want this sort of thing they can bake it themselves in the SDK with a type that augments a vector reference with a pos,offset pair.
